project_id = "blgjfoyxwszxwiqrsrpw"

[functions.delete-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.log-session]
verify_jwt = false

[functions.daily-multi-account-scan]
verify_jwt = false
